### ISSUE TITLE
Site suggestion - Don't not give the solution

### ISSUE THREAD

**Issue by DIRECTVIRUS** [Jordy3D/Jordy3D.github.io#4]
I suggest adding a don't for not giving the solution when a user fixes a problem.

Many users online say they fixed it without actively giving steps to follow for another user having the same issue.

This hinders a user from helping themselves and can often frustrate users

it also hinders developers from possibility mitigating said issue in the future

**Comment by Jordy3D** [comment]
Just noticed this was in the wrong repo, recreated at the right one [here](https://github.com/Jordy3D/dont/issues/1)
